import struct
data=open("ecus/simos85/firmware/8R0907551F_Original.bin","rb").read()
N=len(data); BASE=0x80000000; CODE_LO,CODE_HI=0x80020000,0x80200000
def isptr(v): return CODE_LO<=v<CODE_HI and (v&1)==0
runs=[]; i=0
while i+4<=N:
    if i%4==0:
        v=struct.unpack("<I",data[i:i+4])[0]
        if isptr(v):
            j=i; ptrs=[]
            while j+4<=N:
                w=struct.unpack("<I",data[j:j+4])[0]
                if isptr(w): ptrs.append(w); j+=4
                else: break
            if len(ptrs)>=4: runs.append((i,ptrs)); i=j; continue
    i+=4
tgt=set(p for _,pl in runs for p in pl)
com=[(o,p) for o,p in runs if len(p)==5 and (0x801d0360 in p or 0x801d0364 in p)]
canmo=[(o,p) for o,p in runs if any(0x801d2940<=x<0x801d2a00 for x in p)]
out=[]
out.append("# Simos8.5 function-pointer DISPATCH-TABLE map (8R0907551F)\n")
out.append("Recovered by scanning flash for runs of >=4 consecutive word-aligned code pointers")
out.append("(0x80020000-0x80200000, even). These are the jump/dispatch tables through which the")
out.append("CAN/Com/ACC subsystem is invoked indirectly — the reason so much of it is unlinked by")
out.append("static call-graph analysis. Generated by scratchpad/gen_tablemap.py over the OBD bin.\n")
out.append(f"- **{len(runs)} tables**, **{len(tgt)} unique code-pointer targets**.")
out.append("- CAUTION: some runs are switch/jump tables (targets are mid-function labels, NOT function")
out.append("  entries) — do NOT bulk-create functions at every target (20-43% are labels/data). The")
out.append("  reliable new-function source is runtime call-target logging (EmulBoot 'call X -> Y').\n")
out.append("## Com per-message IPDU descriptor tables (5-tuple)")
out.append("Layout `{process_fn, b, CHKSUM=0x801d0360(stub), c, COUNTER=0x801d0364(stub)}` — the stub")
out.append("chksum/counter confirm periodic RX/TX E2E is NOT enforced here (see RESULTS UPDATE 32).")
out.append(f"{len(com)} such descriptors:\n")
out.append("| descriptor @ | process_fn | b | c |")
out.append("|---|---|---|---|")
for o,p in com:
    out.append(f"| {BASE+o:#x} | {p[0]:#x} | {p[1]:#x} | {p[3]:#x} |")
out.append("\n## CAN message-object (canmo) dispatch tables")
out.append("Tables referencing the canmo_10x handlers (0x801d294c-0x801d2974); canmo_10c_TSK_02")
out.append("=0x801d2956 (decel out, ipdu 3), canmo_10a_TSK_01=0x801d2968 (ipdu 6). Master canmo")
out.append("dispatch is @0x80082f18 (per handler comments).\n")
for o,p in canmo:
    out.append(f"- @{BASE+o:#x} len={len(p)}: {' '.join(f'{x:#x}' for x in p)}")
open("ecus/simos85/maps/dispatch_tables.md","w").write("\n".join(out)+"\n")
print("wrote ecus/simos85/maps/dispatch_tables.md")
print(f"tables={len(runs)} targets={len(tgt)} com5tuple={len(com)} canmo={len(canmo)}")
